"""V4 — closest-point morph + tangent surface relaxation (experimental)."""

from graphite.explicit.compare_v4_surface_relax.generate_compare_v4 import (
    DEFAULT_CELL_SIZE,
    DEFAULT_MAX_PROJECTION_FACTOR,
    DEFAULT_RULE_NAME,
    DEFAULT_STAIR_STEP_GATE_FACTOR,
    DEFAULT_STRUT_RADIUS,
    DEFAULT_SURFACE_RELAX_ALPHA,
    DEFAULT_SURFACE_RELAX_ITERATIONS,
    DEFAULT_SURFACE_RELAX_MAX_TRAVEL_FACTOR,
    DEFAULT_VOLUME_FRACTION,
    PROJECTION_MODE,
    generate_compare_v4,
)

__all__ = [
    "DEFAULT_CELL_SIZE",
    "DEFAULT_MAX_PROJECTION_FACTOR",
    "DEFAULT_RULE_NAME",
    "DEFAULT_STAIR_STEP_GATE_FACTOR",
    "DEFAULT_STRUT_RADIUS",
    "DEFAULT_SURFACE_RELAX_ALPHA",
    "DEFAULT_SURFACE_RELAX_ITERATIONS",
    "DEFAULT_SURFACE_RELAX_MAX_TRAVEL_FACTOR",
    "DEFAULT_VOLUME_FRACTION",
    "PROJECTION_MODE",
    "generate_compare_v4",
]
