"""
Graphite Continuous Pentamode (Meta-Fluid) Generator

Implements 4-coordinated Milton-Cherkaev diamond cubic metamaterial networks
with parameterized biconical strut envelopes and hierarchical sub-truss infill:
- Diamond cubic symmetry (Fd-3m, tetrahedral coordination Z = 4, bond angle ~109.47 deg).
- Biconical envelope: r(t) = r_min + 4*(r_max - r_min)*t*(1 - t).
- Hierarchical sub-truss infill (tetrahedral and C15-inspired) maximizing I_eff and r_g.
- Polymorphic output formats: LatticeGraph, ImplicitField, and watertight Trimesh.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable, Sequence
import numpy as np
from scipy.spatial import cKDTree
import trimesh
import manifold3d as m3d

from graphite.explicit.geometry_module import (
    _trimesh_to_manifold,
    _manifold_to_trimesh,
    _rotation_align_local_z_to_unit,
    _affine_rows_from_R_t,
    generate_geometry,
)


@dataclass
class LatticeGraph:
    """Represents an explicit 1D graph network of nodes, struts, and radii."""
    nodes: np.ndarray  # shape: (N, 3), dtype: float64
    struts: np.ndarray  # shape: (M, 2), dtype: int64
    radii: np.ndarray | float = 0.5  # shape: (M,) or float
    metadata: dict = field(default_factory=dict)

    def to_trimesh(self, add_spheres: bool = True) -> trimesh.Trimesh:
        """Construct a watertight solid mesh from this graph via Manifold3D."""
        return generate_geometry(
            nodes=self.nodes,
            struts=self.struts,
            strut_radius=self.radii,
            add_spheres=add_spheres,
            crop_to_boundary=False,
        )

    def export_inp(self, path: str | Path, job_name: str = "PENTAMODE") -> None:
        """Export the graph as an Abaqus/CalculiX beam element input file (.inp)."""
        p = Path(path)
        p.parent.mkdir(parents=True, exist_ok=True)
        with open(p, "w", encoding="utf-8") as f:
            f.write(f"*HEADING\n** Job: {job_name}\n** Generated by Graphite Pentamode Engine\n")
            f.write("*NODE\n")
            for i, node in enumerate(self.nodes, start=1):
                f.write(f"{i}, {node[0]:.6f}, {node[1]:.6f}, {node[2]:.6f}\n")
            f.write("*ELEMENT, TYPE=B31, ELSET=STRUTS\n")
            for i, (u, v) in enumerate(self.struts, start=1):
                f.write(f"{i}, {u + 1}, {v + 1}\n")
            f.write("*END STEP\n")


@dataclass
class ImplicitField:
    """Represents a 3D scalar distance field grid for isosurface extraction."""
    field: np.ndarray  # shape: (Nx, Ny, Nz), dtype: float32 or float64
    origin: tuple[float, float, float]  # (xmin, ymin, zmin)
    spacing: tuple[float, float, float]  # (dx, dy, dz)
    metadata: dict = field(default_factory=dict)

    def to_trimesh(self, level: float = 0.0) -> trimesh.Trimesh:
        """Extract a watertight boundary isosurface mesh at zero-crossing."""
        from graphite.implicit.meshing_backends import extract_isosurface
        res = extract_isosurface(
            field=self.field,
            spacing=self.spacing,
            origin=self.origin,
            level=level,
            backend="auto",
        )
        return res.mesh


def generate_diamond_cubic_graph(
    bounds: tuple[tuple[float, float, float], tuple[float, float, float]],
    unit_cell_size: float,
) -> tuple[np.ndarray, np.ndarray]:
    """
    Generate the diamond cubic lattice (Fd-3m) nodes and struts within the given bounds.

    Parameters:
        bounds: ((xmin, ymin, zmin), (xmax, ymax, zmax)) bounding box in mm.
        unit_cell_size: Conventional cubic unit cell side length 'a' in mm.

    Returns:
        nodes: (N, 3) float64 array of nodal coordinates.
        struts: (M, 2) int64 array of bond indices.
    """
    (xmin, ymin, zmin), (xmax, ymax, zmax) = bounds
    a = float(unit_cell_size)
    if a <= 1e-6:
        raise ValueError(f"unit_cell_size must be positive, got {a}")

    # Number of repetitions needed to comfortably cover bounds
    nx = int(np.ceil((xmax - xmin) / a)) + 1
    ny = int(np.ceil((ymax - ymin) / a)) + 1
    nz = int(np.ceil((zmax - zmin) / a)) + 1

    # Conventional diamond cubic cell contains 8 basis atoms:
    # Set 1 (FCC positions)
    b1 = np.array([
        [0.0, 0.0, 0.0],
        [0.0, 0.5, 0.5],
        [0.5, 0.0, 0.5],
        [0.5, 0.5, 0.0],
    ], dtype=np.float64) * a

    # Set 2 (shifted by (1/4, 1/4, 1/4)*a)
    b2 = np.array([
        [0.25, 0.25, 0.25],
        [0.25, 0.75, 0.75],
        [0.75, 0.25, 0.75],
        [0.75, 0.75, 0.25],
    ], dtype=np.float64) * a

    raw_nodes = []
    for i in range(-1, nx + 1):
        for j in range(-1, ny + 1):
            for k in range(-1, nz + 1):
                offset = np.array([xmin + i * a, ymin + j * a, zmin + k * a], dtype=np.float64)
                for pt in b1:
                    raw_nodes.append(offset + pt)
                for pt in b2:
                    raw_nodes.append(offset + pt)

    raw_nodes = np.array(raw_nodes, dtype=np.float64)

    # Deduplicate nodes across cell boundaries
    rounded = np.round(raw_nodes, 4)
    _, first_idx = np.unique(rounded, axis=0, return_index=True)
    all_nodes = raw_nodes[first_idx]

    # Nearest neighbor bond distance in diamond lattice is sqrt(3)/4 * a
    bond_length = (np.sqrt(3.0) / 4.0) * a
    tree = cKDTree(all_nodes)
    pairs = tree.query_pairs(r=bond_length * 1.05)

    valid_struts = []
    for u, v in pairs:
        dist = float(np.linalg.norm(all_nodes[u] - all_nodes[v]))
        if abs(dist - bond_length) < 0.02 * a:
            valid_struts.append((min(u, v), max(u, v)))

    valid_struts = np.array(valid_struts, dtype=np.int64)

    # Crop to requested bounding box (keep struts whose midpoint is within bounds)
    if len(valid_struts) == 0:
        return np.zeros((0, 3)), np.zeros((0, 2), dtype=np.int64)

    midpoints = 0.5 * (all_nodes[valid_struts[:, 0]] + all_nodes[valid_struts[:, 1]])
    inside_mask = (
        (midpoints[:, 0] >= xmin - 1e-4) & (midpoints[:, 0] <= xmax + 1e-4) &
        (midpoints[:, 1] >= ymin - 1e-4) & (midpoints[:, 1] <= ymax + 1e-4) &
        (midpoints[:, 2] >= zmin - 1e-4) & (midpoints[:, 2] <= zmax + 1e-4)
    )

    cropped_struts = valid_struts[inside_mask]
    if len(cropped_struts) == 0:
        return np.zeros((0, 3)), np.zeros((0, 2), dtype=np.int64)

    used_node_indices = np.unique(cropped_struts)
    remap = {old: new for new, old in enumerate(used_node_indices)}
    nodes = all_nodes[used_node_indices]
    struts = np.array([[remap[u], remap[v]] for u, v in cropped_struts], dtype=np.int64)

    return nodes, struts


def bicone_radius(t: float | np.ndarray, r_min: float, r_max: float) -> float | np.ndarray:
    """
    Evaluate the biconical strut radius profile:
    r(t) = r_min + 4 * (r_max - r_min) * t * (1 - t) for normalized coordinate t in [0, 1].
    """
    return r_min + 4.0 * (r_max - r_min) * t * (1.0 - t)


def _build_hierarchical_subtruss_strut(
    pA: np.ndarray,
    pB: np.ndarray,
    r_min: float,
    r_max: float,
    sub_element_type: str = "tetrahedral",
    num_stations: int = 3,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    Generate a micro-truss infilling the biconical spindle envelope between pA and pB.
    """
    v = pB - pA
    length = float(np.linalg.norm(v))
    if length <= 1e-8:
        return np.zeros((0, 3)), np.zeros((0, 2), dtype=np.int64), np.zeros(0)

    z_axis = v / length
    # Construct orthogonal frame
    if abs(z_axis[0]) < 0.9:
        ref = np.array([1.0, 0.0, 0.0])
    else:
        ref = np.array([0.0, 1.0, 0.0])
    u_axis = np.cross(z_axis, ref)
    u_axis /= np.linalg.norm(u_axis)
    w_axis = np.cross(z_axis, u_axis)

    nodes_list = [pA]  # index 0: apex A
    struts_list = []
    r_micro = max(0.10, r_min * 0.5)

    # Stations along normalized coordinate t
    # E.g. for 3 stations: t = [0.25, 0.50, 0.75]
    t_stations = np.linspace(0.25, 0.75, num_stations)

    prev_ring_indices = [0]  # starts at apex A

    if sub_element_type == "tetrahedral":
        # 3-fold polygonal cross-sections with alternating twists forming tetrahedra
        for st_idx, t_val in enumerate(t_stations):
            r_env = float(bicone_radius(t_val, r_min, r_max))
            center = pA + t_val * v
            ring_indices = []
            twist = st_idx * (np.pi / 3.0)  # 60 deg twist per station

            for m in range(3):
                theta = m * (2.0 * np.pi / 3.0) + twist
                pos = center + r_env * (np.cos(theta) * u_axis + np.sin(theta) * w_axis)
                idx = len(nodes_list)
                nodes_list.append(pos)
                ring_indices.append(idx)

            # Connect perimeter of current ring
            for m in range(3):
                struts_list.append((ring_indices[m], ring_indices[(m + 1) % 3]))

            # Connect to previous ring or apex
            if len(prev_ring_indices) == 1:
                # Connected to apex A
                for idx in ring_indices:
                    struts_list.append((prev_ring_indices[0], idx))
            else:
                # Connect cross-diagonals (forming tetrahedral cells)
                for m in range(3):
                    struts_list.append((prev_ring_indices[m], ring_indices[m]))
                    struts_list.append((prev_ring_indices[m], ring_indices[(m + 1) % 3]))

            prev_ring_indices = ring_indices

        # Connect last ring to apex B
        idx_B = len(nodes_list)
        nodes_list.append(pB)
        for idx in prev_ring_indices:
            struts_list.append((idx, idx_B))

    elif sub_element_type == "c15_subtruss":
        # C15-inspired sub-truss: 4-fold outer cage plus central longitudinal core spine
        core_nodes = []
        for st_idx, t_val in enumerate(t_stations):
            r_env = float(bicone_radius(t_val, r_min, r_max))
            center = pA + t_val * v
            c_idx = len(nodes_list)
            nodes_list.append(center)
            core_nodes.append(c_idx)

            ring_indices = []
            twist = st_idx * (np.pi / 4.0)
            for m in range(4):
                theta = m * (np.pi / 2.0) + twist
                pos = center + r_env * (np.cos(theta) * u_axis + np.sin(theta) * w_axis)
                idx = len(nodes_list)
                nodes_list.append(pos)
                ring_indices.append(idx)
                # Radial spoke from core to envelope
                struts_list.append((c_idx, idx))

            # Ring perimeter
            for m in range(4):
                struts_list.append((ring_indices[m], ring_indices[(m + 1) % 4]))

            # Longitudinal & diagonal connections
            if len(prev_ring_indices) == 1:
                for idx in ring_indices:
                    struts_list.append((prev_ring_indices[0], idx))
                struts_list.append((prev_ring_indices[0], c_idx))
            else:
                for m in range(4):
                    struts_list.append((prev_ring_indices[m], ring_indices[m]))
                    struts_list.append((prev_ring_indices[m], ring_indices[(m + 1) % 4]))
                struts_list.append((core_nodes[-2], c_idx))

            prev_ring_indices = ring_indices

        idx_B = len(nodes_list)
        nodes_list.append(pB)
        for idx in prev_ring_indices:
            struts_list.append((idx, idx_B))
        struts_list.append((core_nodes[-1], idx_B))

    else:  # fallback solid / single strut
        nodes_list = [pA, pB]
        struts_list = [(0, 1)]
        r_micro = r_min

    nodes_arr = np.array(nodes_list, dtype=np.float64)
    struts_arr = np.array(struts_list, dtype=np.int64)
    radii_arr = np.full(len(struts_arr), r_micro, dtype=np.float64)

    return nodes_arr, struts_arr, radii_arr


def generate_pentamode_lattice(
    bounds: tuple[tuple[float, float, float], tuple[float, float, float]],
    unit_cell_size: float,
    r_min: float,
    r_max: float,
    hierarchical: bool = False,
    sub_element_type: str = "tetrahedral",
    output_format: str = "graph",
    grid_resolution: int = 64,
    crop_to_bounds: bool = False,
) -> LatticeGraph | ImplicitField | trimesh.Trimesh:
    """
    Generate a 4-coordinated Milton-Cherkaev diamond pentamode lattice.

    Parameters:
        bounds: ((xmin, ymin, zmin), (xmax, ymax, zmax)) domain box in mm.
        unit_cell_size: Conventional diamond cubic unit cell length 'a' in mm.
        r_min: Hinge neck radius at macro nodes in mm.
        r_max: Maximum mid-span envelope radius in mm.
        hierarchical: If True, infills each bicone with a meso-scale sub-truss.
        sub_element_type: 'tetrahedral' | 'c15_subtruss' | 'solid'.
        output_format: 'graph' | 'implicit_sdf' | 'mesh'.
        grid_resolution: Voxel resolution per axis for 'implicit_sdf'.

    Returns:
        LatticeGraph, ImplicitField, or watertight trimesh.Trimesh.
    """
    nodes, struts = generate_diamond_cubic_graph(bounds=bounds, unit_cell_size=unit_cell_size)

    if len(struts) == 0:
        raise ValueError(f"No pentamode struts generated within bounds {bounds} with unit_cell_size={unit_cell_size}")

    # 1. GRAPH OUTPUT
    if output_format == "graph":
        if not hierarchical:
            # Piecewise discrete bicones or single macro-struts with radius metadata
            return LatticeGraph(
                nodes=nodes,
                struts=struts,
                radii=float(r_min),
                metadata={
                    "r_min": float(r_min),
                    "r_max": float(r_max),
                    "unit_cell_size": float(unit_cell_size),
                    "hierarchical": False,
                },
            )
        else:
            # Assemble all hierarchical sub-trusses into a single composite graph
            sub_nodes_list = []
            sub_struts_list = []
            sub_radii_list = []
            offset = 0

            for u, v in struts:
                pA = nodes[u]
                pB = nodes[v]
                sn, ss, sr = _build_hierarchical_subtruss_strut(
                    pA, pB, r_min=r_min, r_max=r_max, sub_element_type=sub_element_type
                )
                sub_nodes_list.append(sn)
                sub_struts_list.append(ss + offset)
                sub_radii_list.append(sr)
                offset += len(sn)

            cat_nodes = np.vstack(sub_nodes_list)
            cat_struts = np.vstack(sub_struts_list)
            cat_radii = np.concatenate(sub_radii_list)

            # Deduplicate nodes across adjoining macro-struts
            rounded = np.round(cat_nodes, 4)
            _, first_idx, inv = np.unique(rounded, axis=0, return_index=True, return_inverse=True)
            welded_nodes = cat_nodes[first_idx]
            welded_struts = inv[cat_struts]
            welded_struts = np.sort(welded_struts, axis=1)
            valid_mask = welded_struts[:, 0] != welded_struts[:, 1]
            welded_struts = welded_struts[valid_mask]
            welded_radii = cat_radii[valid_mask]

            # Remove duplicate struts
            _, unique_strut_idx = np.unique(welded_struts, axis=0, return_index=True)
            final_struts = welded_struts[unique_strut_idx]
            final_radii = welded_radii[unique_strut_idx]

            return LatticeGraph(
                nodes=welded_nodes,
                struts=final_struts,
                radii=final_radii,
                metadata={
                    "r_min": float(r_min),
                    "r_max": float(r_max),
                    "hierarchical": True,
                    "sub_element_type": sub_element_type,
                },
            )

    # 2. IMPLICIT SDF OUTPUT
    elif output_format == "implicit_sdf":
        (xmin, ymin, zmin), (xmax, ymax, zmax) = bounds
        res = int(grid_resolution)
        xs = np.linspace(xmin, xmax, res)
        ys = np.linspace(ymin, ymax, res)
        zs = np.linspace(zmin, zmax, res)
        spacing = (float((xmax - xmin) / (res - 1)), float((ymax - ymin) / (res - 1)), float((zmax - zmin) / (res - 1)))
        origin = (float(xmin), float(ymin), float(zmin))

        grid_x, grid_y, grid_z = np.meshgrid(xs, ys, zs, indexing="ij")
        grid_pts = np.column_stack([grid_x.ravel(), grid_y.ravel(), grid_z.ravel()])

        # Exact distance to biconical surfaces
        # Initialize distance field to large positive number (outside)
        min_sdf = np.full(len(grid_pts), 1e6, dtype=np.float64)

        for u, v in struts:
            pA = nodes[u]
            pB = nodes[v]
            seg_vec = pB - pA
            L = float(np.linalg.norm(seg_vec))
            if L <= 1e-8:
                continue
            u_dir = seg_vec / L

            # Vectorized projection of all grid points onto this strut segment
            diff = grid_pts - pA
            proj = np.dot(diff, u_dir)
            t = np.clip(proj / L, 0.0, 1.0)
            closest = pA + t[:, None] * seg_vec
            dist_to_axis = np.linalg.norm(grid_pts - closest, axis=1)

            # Local biconical radius
            r_local = bicone_radius(t, r_min=r_min, r_max=r_max)
            sdf_strut = dist_to_axis - r_local
            min_sdf = np.minimum(min_sdf, sdf_strut)

        sdf_field = min_sdf.reshape((res, res, res)).astype(np.float32)
        return ImplicitField(field=sdf_field, origin=origin, spacing=spacing)

    # 3. SOLID WATERTIGHT MESH OUTPUT
    elif output_format == "mesh":
        if hierarchical:
            # Generate mesh from hierarchical sub-truss
            graph = generate_pentamode_lattice(
                bounds=bounds,
                unit_cell_size=unit_cell_size,
                r_min=r_min,
                r_max=r_max,
                hierarchical=True,
                sub_element_type=sub_element_type,
                output_format="graph",
            )
            mesh = graph.to_trimesh(add_spheres=True)
            if crop_to_bounds:
                from graphite.explicit.geometry_module import _trimesh_to_manifold
                m = _trimesh_to_manifold(mesh)
                (xmin, ymin, zmin), (xmax, ymax, zmax) = bounds
                box = m3d.Manifold.cube([xmax - xmin, ymax - ymin, zmax - zmin]).translate((xmin, ymin, zmin))
                mesh = _manifold_to_trimesh(m ^ box)
            return mesh

        # Build solid biconical envelope mesh using Manifold3D frustum segments
        parts: list[m3d.Manifold] = []
        n_segments = 10  # 10 frustum segments per bicone

        for u, v in struts:
            pA = nodes[u]
            pB = nodes[v]
            seg_vec = pB - pA
            L = float(np.linalg.norm(seg_vec))
            if L <= 1e-8:
                continue

            z_unit = seg_vec / L
            R_mat = _rotation_align_local_z_to_unit(z_unit)

            for k in range(n_segments):
                t0 = k / float(n_segments)
                t1 = (k + 1) / float(n_segments)
                r0 = float(bicone_radius(t0, r_min, r_max))
                r1 = float(bicone_radius(t1, r_min, r_max))
                pos0 = pA + t0 * seg_vec
                pos1 = pA + t1 * seg_vec
                mid = 0.5 * (pos0 + pos1)
                h_seg = (L / float(n_segments)) * 1.05

                aff = _affine_rows_from_R_t(R_mat, mid)
                frustum = m3d.Manifold.cylinder(
                    height=h_seg,
                    radius_low=r0,
                    radius_high=r1,
                    circular_segments=16,
                    center=True,
                ).transform(aff)
                parts.append(frustum)

        # Nodal spherical fillets of radius r_min at all vertex junctions
        for pt in nodes:
            sphere = m3d.Manifold.sphere(r_min * 1.05, circular_segments=16).translate(tuple(float(c) for c in pt))
            parts.append(sphere)

        composed = m3d.Manifold.batch_boolean(parts, m3d.OpType.Add)
        if crop_to_bounds:
            (xmin, ymin, zmin), (xmax, ymax, zmax) = bounds
            box = m3d.Manifold.cube([xmax - xmin, ymax - ymin, zmax - zmin]).translate((xmin, ymin, zmin))
            composed = composed ^ box
        return _manifold_to_trimesh(composed)

    else:
        raise ValueError(f"Unknown output_format '{output_format}'. Expected 'graph', 'implicit_sdf', or 'mesh'.")
