"""
Aristo Configuration — AristoConfig Dataclass & Material Presets

Aristo is Graphite's FEA/FEM analysis module. Named after Aristo Werke,
the slide-rule manufacturer — a tongue-in-cheek nod since Abaqus is taken.

All physical units follow the Graphite project convention:
    mm  for length
    MPa for stress and Young's modulus (N/mm²)
    N   for force

Author: Graphite / Aristo Project
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Tuple


# ---------------------------------------------------------------------------
# Material presets  (E in MPa, ν dimensionless)
# ---------------------------------------------------------------------------

MATERIAL_PRESETS: dict[str, tuple[float, float]] = {
    "Formlabs Tough 2000": (2200.0, 0.38),
    "Nylon 12 (SLS)":     (1500.0, 0.40),
    "ABS":               (2000.0, 0.35),
    "PLA":               (3500.0, 0.36),
    "Resin (SLA)":       (2800.0, 0.38),
    "Ti6Al4V":           (113_800.0, 0.34),
}


# ---------------------------------------------------------------------------
# AristoConfig
# ---------------------------------------------------------------------------


@dataclass
class AristoConfig:
    """
    Configuration for a single Aristo FEA run.

    Parameters
    ----------
    youngs_modulus : float
        Young's modulus (MPa). Default ≈ SLA photopolymer resin.
    poisson_ratio : float
        Poisson's ratio (dimensionless, must be in (0, 0.5)).
        Default 0.38 for typical photopolymer resin.
    fea_mesh_resolution : float
        Target maximum tetrahedral edge length (mm) for the *dedicated* FEA mesh.
        This is generated by a separate gmsh call, independent of the lattice
        scaffold cell size. Finer = more accurate, more RAM/time. Default: 1.0 mm.
    load_direction : tuple[float, float, float]
        Uniaxial load direction vector (need not be unit; normalized internally).
        Convention: (0, 0, -1) = compression in -Z (top face loaded downward).
        Phase 1 supports uniaxial only. Multi-axis planned for Phase 2.
    load_magnitude : float
        Pressure magnitude (N/mm²) applied to the loaded surface faces.
        Results are normalized to max Von Mises, so absolute magnitude only
        affects the displacement scale — not the stress distribution shape.
    load_mode : str
        Determines which faces of the selected surface ID receive the load:
        - 'full': Apply to all faces in the surface ID (default).
        - 'tension_half': apply only to faces whose normal aligns with load_direction
          (useful for pins pulling on a hole).
        - 'compression_half': apply only to faces pointing against load_direction
          (useful for pins pushing on a hole).
    fixed_face_ids : list[int]
        Trimesh face indices for the fixed (zero-displacement) support surface.
        Leave empty to use the Phase-1 heuristic (auto-detected from load direction).
        Phase 1b (boundary_detection.py) will replace the heuristic.
    load_face_ids : list[int]
        Trimesh face indices for the loaded surface.
        Leave empty to use the Phase-1 heuristic.
    bc_z_band_fraction : float | None
        When set (e.g. 0.01), select fixed/load faces by axis position in a band
        of this fraction of total mesh height at each end, instead of the
        quantile heuristic. With ``bc_load_mode='flat_top'``, applies to the
        fixed (bottom) support only.
    bc_load_mode : str
        ``z_band`` (default): symmetric top/bottom Z-bands. ``flat_top``: bottom
        Z-band fixed support; load faces at ``z_max - bc_top_z_tolerance_mm`` with
        ``normal_z > bc_top_normal_z_min``. ``flat_top_vertex_plane``: load faces
        with all vertices on the dominant top Z level (≥ ``bc_top_min_vertices_at_plane``
        surface nodes at exact Z) and ``normal_z > bc_top_normal_z_min``. Fixed faces
        use the symmetric bottom vertex plane with ``normal_z < -bc_bottom_normal_z_min``.
    bc_top_z_tolerance_mm : float
        Positional tolerance below ``z_max`` for flat-top load face selection (mm).
        Ignored when ``bc_load_mode='flat_top_vertex_plane'``.
    bc_top_normal_z_min : float
        Minimum upward normal Z-component for flat-top load faces.
    bc_bottom_normal_z_min : float
        Minimum downward normal magnitude for vertex-plane fixed faces
        (``normal_z < -bc_bottom_normal_z_min``).
    bc_top_min_vertices_at_plane : int
        For ``flat_top_vertex_plane``: minimum surface-node count at the chosen
        cap Z (exact coordinate match).
    fea_quality_mode : str
        ``quick``: keep all tets in the stiffness solve; exclude poor tets from
        stress statistics and visualization only.
        ``thorough``: remesh with gmsh optimization and tighter sizing until the
        poor-tet fraction falls below ``thorough_max_poor_fraction`` (or max
        attempts).
    min_tet_volume_mm3 : float | None
        Absolute minimum tet volume (mm³) for stress post-processing. When None,
        uses ``min_tet_volume_fraction`` × median tet volume.
    min_tet_volume_fraction : float
        Fraction of median tet volume used as volume floor when absolute min unset.
    max_tet_aspect_ratio : float
        Max edge-length aspect ratio for a tet to count as stress-valid.
    thorough_remesh_max_attempts : int
        Max gmsh remesh attempts in ``thorough`` mode.
    thorough_max_poor_fraction : float
        Target upper bound on poor-tet fraction before stopping thorough remesh.
    thorough_use_netgen_optimize : bool
        When False (default for lattices), thorough mode only retries with tighter
        sizing. Netgen optimize on discrete STL soups can create giant diagonal tets.
    max_tet_edge_factor : float
        Max longest edge = this factor × ``fea_mesh_resolution`` (stress gate).
    max_tet_edge_mm : float | None
        Optional absolute max edge override (mm).
    max_tet_volume_fraction : float
        Reject tets larger than this multiple of median tet volume.
    giant_tet_edge_factor : float
        Thorough remesh rejects meshes whose max edge exceeds
        ``max(2.2 mm, factor × fea_mesh_resolution)``.
    giant_tet_edge_mm : float | None
        Optional absolute max-edge override for thorough remesh rejection.
    stress_representation : str
        ``nodal_averaged`` (default): volume-weighted nodal recovery; peaks and
        normalization use the nodal field. ``element_raw``: Phase-1 per-element
        constants normalized by element peak.
    fea_gmsh_mesh_mode : str | None
        Gmsh volume-mesh strategy. Default ``single_surface`` (implicit-first).
        Set ``tpms`` or ``lattice`` for **developer STL** Mirae-style classifySurfaces.
    fea_input_mode : str
        ``implicit`` (default): evaluate implicit field → MC skin in memory.
        ``stl``: boundary loaded from an STL file (developer / legacy path).
    fea_gmsh_adaptive_curvature : bool
        When True (default), TPMS/classify meshing uses Gmsh
        ``CharacteristicLengthFromCurvature`` with ``fea_gmsh_char_length_min``
        / ``max`` instead of scaling uniform ``Mesh.MeshSize*`` from ``h``.
    fea_gmsh_char_length_min : float
        Absolute minimum characteristic length on tight lattice curves (mm).
    fea_gmsh_char_length_max : float
        Absolute maximum characteristic length on flat caps (mm).
    fea_gmsh_min_elements_per_two_pi : int
        ``Mesh.MinimumElementsPerTwoPi`` for curvature-based sizing.
    fea_gmsh_classify_only : bool
        When True, do not fall back to single-surface meshing if classify fails.
        Default False (implicit-first); Mirae dev scripts set True explicitly.
    fea_clean_stl_surface : bool
        When True (or ``ARISTO_CLEAN_STL_SURFACE=1``), run Open3D isotropic
        surface remesh on the STL skin before gmsh volume meshing. Targets
        equilateral cap triangles at ``fea_mesh_resolution`` to reduce FEA
        stress speckling from needle boundary elements.
    fea_surface_clean_py312_worker : bool
        When Open3D is missing in the active interpreter (e.g. Python 3.13),
        auto-create ``.venv312/`` with Python 3.12 and run ``clean_stl_surface.py``
        in a subprocess. Set ``ARISTO_SURFACE_CLEAN_DISABLE_PY312=1`` to skip.
    fea_surface_clean_venv312_dir : str | None
        Override path to the Python 3.12 worker venv (default: repo ``.venv312/``).
        Env override: ``ARISTO_SURFACE_CLEAN_VENV312``.
    fea_linear_solver : str | None
        Sparse direct solver for ``K u = F``. ``auto`` (default): PARDISO when
        ``pypardiso`` is installed, else SciPy ``spsolve``. Set ``scipy`` or
        ``pardiso`` explicitly. Env override: ``ARISTO_LINEAR_SOLVER``.

    Gradient Adapter Hard Constraints
    ----------------------------------
    These are enforced in stress_mapper.py (Phase 1c) before the gradient is
    handed to any lattice engine. They are stored here so the UI can display
    the locked values clearly.

    vf_floor : float
        Minimum solid fraction for low-stress regions (default 10%).
    vf_cap : float
        **HARD CAP** — solid fraction never exceeds this value. Max allowed: 0.50.
    min_strut_radius : float
        Minimum explicit strut radius (mm). Hard floor = 0.25 mm (500 µm diameter).
    min_implicit_cell_size : float
        Minimum TPMS unit-cell size (mm). Pore-size field never falls below this.
    """

    youngs_modulus: float = 2800.0
    poisson_ratio: float = 0.38
    fea_mesh_resolution: float = 1.0

    load_direction: Tuple[float, float, float] = (0.0, 0.0, -1.0)
    load_magnitude: float = 1.0
    load_mode: str = "full"  # 'full', 'tension_half', 'compression_half'

    # Face IDs (Phase 1b: boundary_detection.py; Phase 1: heuristic used when empty)
    fixed_face_ids: list = field(default_factory=list)
    load_face_ids: list = field(default_factory=list)
    bc_z_band_fraction: float | None = None
    bc_load_mode: str = "z_band"
    bc_top_z_tolerance_mm: float = 1e-4
    bc_top_normal_z_min: float = 0.99
    bc_bottom_normal_z_min: float = 0.99
    bc_top_min_vertices_at_plane: int = 100

    fea_quality_mode: str = "quick"
    min_tet_volume_mm3: float | None = None
    min_tet_volume_fraction: float = 0.01
    max_tet_aspect_ratio: float = 20.0
    thorough_remesh_max_attempts: int = 3
    thorough_max_poor_fraction: float = 0.005
    thorough_use_netgen_optimize: bool = False
    max_tet_edge_factor: float = 12.0
    max_tet_edge_mm: float | None = None
    max_tet_volume_fraction: float = 50.0
    giant_tet_edge_factor: float = 6.0
    giant_tet_edge_mm: float | None = None
    stress_representation: str = "nodal_averaged"
    fea_input_mode: str = "implicit"
    fea_gmsh_mesh_mode: str | None = "single_surface"
    fea_sdf_voxel_pitch: float | None = None
    fea_gmsh_adaptive_curvature: bool = True
    fea_gmsh_char_length_min: float = 0.08
    fea_gmsh_char_length_max: float = 0.8
    fea_gmsh_min_elements_per_two_pi: int = 15
    fea_gmsh_classify_only: bool = False
    fea_clean_stl_surface: bool = False
    fea_surface_clean_py312_worker: bool = True
    fea_surface_clean_venv312_dir: str | None = None
    fea_linear_solver: str | None = None

    # Gradient adapter hard constraints (enforced downstream in stress_mapper.py)
    vf_floor: float = 0.10
    vf_cap: float = 0.50          # Hard cap — never exceed 50%
    min_strut_radius: float = 0.25    # mm  (= 500 µm diameter)
    min_implicit_cell_size: float = 1.0  # mm

    # ---------------------------------------------------------------------------
    # Validation
    # ---------------------------------------------------------------------------

    def __post_init__(self) -> None:
        if self.youngs_modulus <= 0.0:
            raise ValueError(
                f"youngs_modulus must be positive, got {self.youngs_modulus} MPa."
            )
        if not (0.0 < self.poisson_ratio < 0.5):
            raise ValueError(
                f"poisson_ratio must be in (0, 0.5) for a physically valid "
                f"isotropic solid, got {self.poisson_ratio}."
            )
        if self.fea_mesh_resolution <= 0.0:
            raise ValueError(
                f"fea_mesh_resolution must be positive, got {self.fea_mesh_resolution} mm."
            )
        if not (0.0 < self.vf_floor < self.vf_cap <= 0.50):
            raise ValueError(
                f"Gradient constraints must satisfy:  0 < vf_floor < vf_cap <= 0.50. "
                f"Got vf_floor={self.vf_floor}, vf_cap={self.vf_cap}."
            )
        if self.min_strut_radius < 0.25:
            raise ValueError(
                f"min_strut_radius must be ≥ 0.25 mm (500 µm diameter). "
                f"Got {self.min_strut_radius} mm."
            )
        if self.min_implicit_cell_size < 1.0:
            raise ValueError(
                f"min_implicit_cell_size must be ≥ 1.0 mm. "
                f"Got {self.min_implicit_cell_size} mm."
            )
        if self.load_magnitude <= 0.0:
            raise ValueError(
                f"load_magnitude must be positive, got {self.load_magnitude}."
            )
        if self.load_mode not in ("full", "tension_half", "compression_half"):
            raise ValueError(
                f"load_mode must be 'full', 'tension_half', or 'compression_half'. "
                f"Got {self.load_mode}."
            )
        if self.bc_z_band_fraction is not None and not (
            0.0 < self.bc_z_band_fraction < 0.5
        ):
            raise ValueError(
                f"bc_z_band_fraction must be in (0, 0.5), got {self.bc_z_band_fraction}."
            )
        if self.bc_load_mode not in ("z_band", "flat_top", "flat_top_vertex_plane"):
            raise ValueError(
                f"bc_load_mode must be 'z_band', 'flat_top', or 'flat_top_vertex_plane', "
                f"got {self.bc_load_mode!r}."
            )
        if self.fea_input_mode not in ("implicit", "stl"):
            raise ValueError(
                f"fea_input_mode must be 'implicit' or 'stl', got {self.fea_input_mode!r}."
            )
        if self.bc_top_min_vertices_at_plane < 1:
            raise ValueError(
                f"bc_top_min_vertices_at_plane must be >= 1, "
                f"got {self.bc_top_min_vertices_at_plane}."
            )
        if self.bc_top_z_tolerance_mm <= 0.0:
            raise ValueError(
                f"bc_top_z_tolerance_mm must be positive, got {self.bc_top_z_tolerance_mm}."
            )
        if not (0.0 < self.bc_top_normal_z_min <= 1.0):
            raise ValueError(
                f"bc_top_normal_z_min must be in (0, 1], got {self.bc_top_normal_z_min}."
            )
        if not (0.0 < self.bc_bottom_normal_z_min <= 1.0):
            raise ValueError(
                f"bc_bottom_normal_z_min must be in (0, 1], got {self.bc_bottom_normal_z_min}."
            )
        if self.fea_quality_mode not in ("quick", "thorough"):
            raise ValueError(
                f"fea_quality_mode must be 'quick' or 'thorough', "
                f"got {self.fea_quality_mode!r}."
            )
        if self.fea_gmsh_mesh_mode is not None:
            allowed = (
                "single_surface",
                "single_only",
                "classify",
                "tpms",
                "lattice",
                "sdf",
                "sdf_mc",
                "voxel",
            )
            key = self.fea_gmsh_mesh_mode.strip().lower()
            if key not in allowed and key not in ("single", "single-only"):
                raise ValueError(
                    f"fea_gmsh_mesh_mode must be one of {allowed}, got {self.fea_gmsh_mesh_mode!r}."
                )
        if self.fea_gmsh_char_length_min <= 0.0:
            raise ValueError(
                f"fea_gmsh_char_length_min must be positive, got {self.fea_gmsh_char_length_min}."
            )
        if self.fea_gmsh_char_length_max <= self.fea_gmsh_char_length_min:
            raise ValueError(
                "fea_gmsh_char_length_max must exceed fea_gmsh_char_length_min."
            )
        if self.fea_gmsh_min_elements_per_two_pi < 1:
            raise ValueError(
                f"fea_gmsh_min_elements_per_two_pi must be >= 1, "
                f"got {self.fea_gmsh_min_elements_per_two_pi}."
            )
        if not (0.0 < self.min_tet_volume_fraction < 1.0):
            raise ValueError(
                f"min_tet_volume_fraction must be in (0, 1), "
                f"got {self.min_tet_volume_fraction}."
            )
        if self.max_tet_aspect_ratio <= 1.0:
            raise ValueError(
                f"max_tet_aspect_ratio must be > 1, got {self.max_tet_aspect_ratio}."
            )
        if self.thorough_remesh_max_attempts < 1:
            raise ValueError(
                f"thorough_remesh_max_attempts must be >= 1, "
                f"got {self.thorough_remesh_max_attempts}."
            )
        if not (0.0 < self.thorough_max_poor_fraction < 0.5):
            raise ValueError(
                f"thorough_max_poor_fraction must be in (0, 0.5), "
                f"got {self.thorough_max_poor_fraction}."
            )
        if self.max_tet_edge_factor <= 0.0:
            raise ValueError(
                f"max_tet_edge_factor must be positive, got {self.max_tet_edge_factor}."
            )
        if self.max_tet_volume_fraction <= 1.0:
            raise ValueError(
                f"max_tet_volume_fraction must be > 1, "
                f"got {self.max_tet_volume_fraction}."
            )
        if self.stress_representation not in ("nodal_averaged", "element_raw"):
            raise ValueError(
                f"stress_representation must be 'nodal_averaged' or 'element_raw', "
                f"got {self.stress_representation!r}."
            )
        if self.fea_linear_solver is not None:
            key = self.fea_linear_solver.strip().lower()
            allowed = ("auto", "scipy", "superlu", "umfpack", "pardiso", "pypardiso", "mkl")
            if key not in allowed:
                raise ValueError(
                    f"fea_linear_solver must be one of auto, scipy, pardiso; got {self.fea_linear_solver!r}."
                )

    # ---------------------------------------------------------------------------
    # Factory helpers
    # ---------------------------------------------------------------------------

    @classmethod
    def from_material_preset(cls, preset_name: str, **kwargs: object) -> "AristoConfig":
        """
        Create an AristoConfig with E and ν populated from a named material preset.

        Parameters
        ----------
        preset_name : str
            Must be one of the keys in MATERIAL_PRESETS:
            'Resin (SLA)', 'Resin (DLP)', 'Nylon 12 (SLS)', 'Ti6Al4V',
            'Stainless 316L', 'ABS'.
        **kwargs
            Any other AristoConfig fields to override (e.g. fea_mesh_resolution=0.5).

        Returns
        -------
        AristoConfig
            With E and ν from the preset; all other fields at their defaults
            (or overridden by kwargs).

        Raises
        ------
        ValueError
            If preset_name is not recognised.
        """
        if preset_name not in MATERIAL_PRESETS:
            opts = "', '".join(MATERIAL_PRESETS)
            raise ValueError(
                f"Unknown material preset '{preset_name}'. "
                f"Available: '{opts}'."
            )
        E, nu = MATERIAL_PRESETS[preset_name]
        return cls(youngs_modulus=E, poisson_ratio=nu, **kwargs)  # type: ignore[arg-type]

    def summary(self) -> str:
        """Return a human-readable one-line summary."""
        return (
            f"AristoConfig | E={self.youngs_modulus} MPa | nu={self.poisson_ratio} | "
            f"mesh={self.fea_mesh_resolution} mm | load_dir={self.load_direction} | "
            f"vf=[{self.vf_floor:.0%},{self.vf_cap:.0%}]"
        )
