# -*- coding: utf-8 -*-
"""TPMS Implant Generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NUvGy0ezMMOHns2RxljPVS_fKtxTdFzS
"""

import numpy as np
from scipy.spatial import cKDTree
from skimage import measure
from stl import mesh
import time

"""
BIOMIMETIC TPMS IMPLANT GENERATOR
---------------------------------
Research Focus: Functionally Graded Bone Implants
Architecture: Blended Voronoi-Hybrid Sheet Split-P (Schwarz P)
Logic:
  This script generates a 3D-printable STL of a TPMS lattice.
  It supports both 'Uniform' (fixed pore size) and 'Graded' (variable pore size)
  modes. The 'Sheet' approach ensures both labyrinths of the bi-continuous
  TPMS remain open for cell migration, unlike 'Solid' TPMS which fills one sub-volume.
"""

# --- CONFIGURATION PARAMETERS ---
SIZE_XY = 2.0     # Base dimensions (mm) - 2mm x 2mm
SIZE_Z = 5.0      # Height (mm) - 5mm tall
TARGET_VF = 0.33  # Target Solid-Fraction (0.33 = 33% material, 67% void)
PORE_SIZE_MM = 0.4  # Uniform pore size: 400um (0.4mm)
RESOLUTION_XY = 180  # Voxel density in X,Y
RESOLUTION_Z = 220   # Voxel density in Z (5mm / 220 ≈ 23um per voxel)

# Gradient: 400um at bottom (z=0) to 800um at top (z=5mm)
GRADIENT_Z_NODES = [0, SIZE_Z]
GRADIENT_P_NODES = [0.4, 0.8]

def get_pore_size_at_z(z, is_graded=False, uniform_p=None):
    """
    Interpolates the target pore size based on height.
    For Split-P, the unit cell length L is approx 2.5 * Pore Size (P).
    """
    if uniform_p is None:
        uniform_p = PORE_SIZE_MM
    if not is_graded:
        return uniform_p
    return np.interp(z, GRADIENT_Z_NODES, GRADIENT_P_NODES)

def generate_seed_cloud(is_graded):
    """
    Generates a stochastic point cloud (seeds).
    For uniform mode: 3D grid of seeds (matches working script).
    For graded mode: 2D layers with height-dependent spacing (400um bottom -> 800um top).
    """
    spacing = PORE_SIZE_MM * 2.5  # L = 2.5 * P for Split-P
    if not is_graded:
        # Uniform: full 3D grid of seeds (cube)
        size = SIZE_XY  # uniform uses cube
        vals = np.arange(-size, size * 2, spacing)
        X_s, Y_s, Z_s = np.meshgrid(vals, vals, vals)
        seeds = np.vstack([X_s.ravel(), Y_s.ravel(), Z_s.ravel()]).T
        seeds += np.random.uniform(-spacing * 0.2, spacing * 0.2, seeds.shape)
    else:
        # Graded: 2D layers with height-dependent spacing
        seeds = []
        z_layers = np.linspace(-0.2, SIZE_Z + 0.2, 80)
        for zl in z_layers:
            p_z = get_pore_size_at_z(zl, is_graded)
            spacing_z = p_z * 2.5
            coords = np.arange(-0.2, SIZE_XY + 0.2, spacing_z)
            XS, YS = np.meshgrid(coords, coords)
            layer_pts = np.vstack([XS.ravel(), YS.ravel(), np.full(XS.size, zl)]).T
            layer_pts[:, :2] += np.random.uniform(-spacing_z*0.25, spacing_z*0.25, (XS.size, 2))
            seeds.extend(layer_pts)
        seeds = np.array(seeds)
    return seeds

def evaluate_field(voxels, seeds, is_graded):
    """
    Core Mathematical Engine - Hybrid Sheet Split-P formula.
    Uses the working formula (T1+T2+T3) which produces proper wall thickness
    via a wider transition region around the zero-crossing.
    IDW blends the 4 nearest seeds for smooth Voronoi-hybrid structure.
    """
    tree = cKDTree(seeds)
    dists, indices = tree.query(voxels, k=4)
    weights = 1.0 / (dists + 1e-6)**4
    weights /= np.sum(weights, axis=1)[:, np.newaxis]

    total_F = np.zeros(len(voxels))
    for i in range(4):
        neighbor_seeds = seeds[indices[:, i]]
        p_local = get_pore_size_at_z(neighbor_seeds[:, 2], is_graded)
        k_local = (2 * np.pi) / (p_local * 2.5)

        dX = voxels[:, 0] - neighbor_seeds[:, 0]
        dY = voxels[:, 1] - neighbor_seeds[:, 1]
        dZ = voxels[:, 2] - neighbor_seeds[:, 2]

        # Hybrid Split-P formula (from working script) - produces proper wall thickness
        T1 = 1.1 * (np.sin(2*k_local*dX)*np.sin(k_local*dZ)*np.cos(k_local*dY) +
                    np.sin(2*k_local*dY)*np.sin(k_local*dX)*np.cos(k_local*dZ) +
                    np.sin(2*k_local*dZ)*np.sin(k_local*dY)*np.cos(k_local*dX))
        T2 = -0.2 * (np.cos(2*k_local*dX)*np.cos(2*k_local*dY) +
                     np.cos(2*k_local*dY)*np.cos(2*k_local*dZ) +
                     np.cos(2*k_local*dZ)*np.cos(2*k_local*dX))
        T3 = -0.4 * (np.cos(k_local*dX) + np.cos(k_local*dY) + np.cos(k_local*dZ))
        total_F += (T1 + T2 + T3) * weights[:, i]

    # Sheet: |F| centers the wall at the zero-crossing
    return np.abs(total_F)

def calibrate_tau(f_grid, target_vf):
    """
    Finds the threshold 'tau' that yields the target Solid Fraction.
    Uses dynamic range 0 to max(F) like the working script.
    """
    tau_range = np.linspace(0, np.max(f_grid), 500)
    best_tau = 0.0
    min_err = 1.0
    for t_test in tau_range:
        current_vf = np.sum(f_grid < t_test) / f_grid.size
        err = abs(current_vf - target_vf)
        if err < min_err:
            min_err = err
            best_tau = t_test
    return best_tau

def generate_lattice(mode="graded"):
    """
    Main Orchestrator.
    Steps: Seed -> Field -> Calibrate -> Mesh -> Export.
    Graded mode: 2mm x 2mm x 5mm, 400um pores at bottom -> 800um at top.
    """
    start_time = time.time()
    is_graded = (mode == "graded")
    print(f"--- Starting {mode.upper()} Lattice Generation ---")

    # 1. Seeds
    seeds = generate_seed_cloud(is_graded)

    # 2. Grid & Field
    if is_graded:
        v_range_xy = np.linspace(0, SIZE_XY, RESOLUTION_XY)
        v_range_z = np.linspace(0, SIZE_Z, RESOLUTION_Z)
        X, Y, Z = np.meshgrid(v_range_xy, v_range_xy, v_range_z, indexing='ij')
        spacing_xy = SIZE_XY / (RESOLUTION_XY - 1)
        spacing_z = SIZE_Z / (RESOLUTION_Z - 1)
    else:
        v_range = np.linspace(0, SIZE_XY, RESOLUTION_XY)
        X, Y, Z = np.meshgrid(v_range, v_range, v_range, indexing='ij')
        spacing_xy = spacing_z = SIZE_XY / (RESOLUTION_XY - 1)

    voxels = np.vstack([X.ravel(), Y.ravel(), Z.ravel()]).T
    f_flat = evaluate_field(voxels, seeds, is_graded)
    f_grid = f_flat.reshape(X.shape)

    # 3. Calibration - tau sets wall thickness via solid fraction
    tau = calibrate_tau(f_grid, TARGET_VF)
    print(f"Calibration: tau={tau:.4f} for {TARGET_VF*100}% VF")

    # 4. Boundary forcing - cap faces as void for manifold mesh
    f_grid[0, :, :] = f_grid[-1, :, :] = 10
    f_grid[:, 0, :] = f_grid[:, -1, :] = 10
    f_grid[:, :, 0] = f_grid[:, :, -1] = 10

    # 5. Meshing (Marching Cubes) - anisotropic spacing for graded
    print("Generating Mesh (Marching Cubes)...")
    verts, faces, _, _ = measure.marching_cubes(
        f_grid, level=tau, spacing=(spacing_xy, spacing_xy, spacing_z)
    )

    # 6. Export to STL
    filename = f"implant_{mode}_{int(TARGET_VF*100)}vf.stl"
    out_mesh = mesh.Mesh(np.zeros(faces.shape[0], dtype=mesh.Mesh.dtype))
    for i, f in enumerate(faces):
        for j in range(3):
            out_mesh.vectors[i][j] = verts[f[j], :]

    out_mesh.save(filename)
    end_time = time.time()
    print(f"SUCCESS: {filename} saved in {end_time - start_time:.1f}s")

if __name__ == "__main__":
    generate_lattice("graded")